### ISSUE TITLE
Suggestion: add Copy button

### ISSUE THREAD

**Issue by navaneethnpk** [ahmedelq/NattyNote#10]
A button to copy all the notes will be very helpful.

**Comment by ahmedelq** [comment]
Hello @navaneethnpk, 
Thanks for the suggestion. 

 How about adding a shortcut instead?  
One shortcut to select all and copy-paste? 
Since we are trying to be minimalists :)


Best,
AE

**Comment by navaneethnpk** [comment]
Yes, a  shortcut is better than button.
